# Generated by Django 5.0.7 on 2024-08-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
