# Generated by Django 5.0.7 on 2024-08-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_stack'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='categories',
            field=models.ManyToManyField(related_name='projects', to='models.category'),
        ),
        migrations.AddField(
            model_name='project',
            name='stacks',
            field=models.ManyToManyField(related_name='projects', to='models.stack'),
        ),
    ]
