# Generated by Django 5.0.7 on 2024-09-04 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_projectvacancy'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='projectvacancy',
            table='project_vacancies',
        ),
    ]
